kevin-lee/just-semver

build.sbt
src/main/scala/just/semver/AdditionalInfo.scala
src/main/scala/just/semver/SemVer.scala
src/test/scala/just/semver/Gens.scala
src/test/scala/just/semver/SemVerSpec.scala

Close #18 - Remove `Identifier`
* `Identifier` adds unnecessary type layer, it can be simply replaced with `List[AlphaNumHyphenGroup]`

Close #18 - Remove Identifier

---

src/main/scala/just/semver/SemVer.scala

Close #20 - Refactor `compare` method for `SemVer` to get rid of the pyramid of doom.

Close #20 - Refactor compare method for SemVer to get rid of the pyramid of doom

---

src/main/scala/just/Common.scala
src/main/scala/just/semver/Anh.scala
src/test/scala/just/semver/SemVerSpec.scala

Fix #32 - `SemVer.compare` does not work for `SemVer` containing `PreRelease`

Fix #32 - SemVer compare does not work for SemVer containing PreRelease

---

README.md
build.sbt
changelogs/0.1.0.md
project/ProjectInfo.scala

* Add `SemVer`
* Remove `Identifier` (#18)
* Refactor `compare` method for `SemVer` (#20)
* Move instance member methods to the companion object (#22)
* Remove `SequenceBasedVersion` (#26)
* Change AlphaNumHyphen to Anh and AlphaNumHyphenGroup to Dsv (#28)
* Add increase for `SemVer` (#36)
* `SemVer` compare does not work for `SemVer` containing `PreRelease` (#32)
* Change group id for publishing to `io.kevinlee` (#12)
* Set up GitHub Actions for CI (#14)
* Add PR templates (#24)

just-semver v0.1.0

---

.github/workflows/release.yml

GitHub Actions to sync to Maven Central after publish to Bintray

GitHub Actions to sync to Maven Central after publish to Bintray

---

build.sbt
project/ProjectInfo.scala
project/plugins.sbt

* Scala `2.12.10` => `2.12.11`
* Since Ammonite does currently not support Scala `2.12.11`, it is disabled for Scala `2.12`.
* Upgraded: sbt-wartremover `2.4.3` => `2.4.5`

Upgraded - Scala and sbt plugin

---

changelogs/0.1.1.md
project/ProjectInfo.scala

* Support Dotty (#58)
* Support Scala `3.0.0-M1` and `3.0.0-M2` (#62)
* Support Scala `3.0.0-M3` (#64)

just-semver v0.1.1

---

changelogs/0.1.2.md

* Support Scala `3.0.0-RC1` (#69)
* Support Scala `3.0.0-RC2` (#72)
* Use `sbt-ci-release` to release (#75)

just-semver v0.1.2

---

changelogs/0.2.0.md

just-semver v0.2.0

---

changelogs/0.3.0.md

* Add some extension methods (#81)
* Add a method to get `(Major, Minor, Patch)` (#82)
* Make `just-semver` 0-dependency project (#86)
* Removed: `just-fp`

just-semver v0.3.0

---

src/test/scala/just/semver/AnhSpec.scala

Fixed: Incorrect test object name for `Anh` - `AlphaNumHyphenSpec` => `AnhSpec`

Fixed: Incorrect test object name for Anh - AlphaNumHyphenSpec => AnhSpec

---

project/plugins.sbt

Close #103 - Upgrade `sbt-devoops` from `2.6.0` to `2.14.0`

Close #103 - Upgrade sbt-devoops from 2.6.0 to 2.14.0

---

build.sbt
project/ProjectInfo.scala
src/main/scala-2/just/semver/SemVer.scala
src/main/scala-2/just/semver/expr/ComparisonOperator.scala
src/main/scala-2/just/semver/matcher/SemVerComparison.scala
src/main/scala-2/just/semver/matcher/SemVerMatcher.scala
src/main/scala-2/just/semver/matcher/SemVerMatchers.scala
src/main/scala-3/just/semver/SemVer.scala
src/main/scala-3/just/semver/expr/ComparisonOperator.scala
src/main/scala-3/just/semver/matcher/SemVerComparison.scala
src/main/scala-3/just/semver/matcher/SemVerMatcher.scala
src/main/scala-3/just/semver/matcher/SemVerMatchers.scala
src/main/scala/just/semver/parser/ComparisonOperatorParser.scala
src/main/scala/just/semver/parser/Parser.scala
src/main/scala/just/semver/parser/ParserError.scala
src/test/scala/just/semver/Gens.scala
src/test/scala/just/semver/SemVerSpec.scala
src/test/scala/just/semver/matcher/Gens.scala
src/test/scala/just/semver/matcher/SemVerComparisonSpec.scala
src/test/scala/just/semver/matcher/SemVerMatcherSpec.scala
src/test/scala/just/semver/matcher/SemVerMatchersSpec.scala
src/test/scala/just/semver/parser/ComparisonOperatorParserSpec.scala
src/test/scala/just/semver/parser/ParserSpec.scala

Close #125 - Add `SemVerMatchers`, `SemVer.matches` and `SemVer.unsafeMatches`

Close #125 - Add SemVerMatchers, SemVer.matches and SemVer.unsafeMatches

---

src/main/scala-2/just/semver/SemVer.scala
src/main/scala-3/just/semver/SemVer.scala
src/test/scala/just/semver/SemVerSpec.scala
src/test/scala/just/semver/matcher/Gens.scala
src/test/scala/just/semver/matcher/SemVerMatcherSpec.scala

Close #129 - Replace `Major`, `Minor` and `Patch` value classes with `opaque type` in Scala 3

Close #129 - Replace Major, Minor and Patch value classes with opaque type in Scala 3

---

src/main/scala-2/just/semver/SemVer.scala
src/main/scala-3/just/semver/SemVer.scala
src/test/scala/just/semver/SemVerSpec.scala
src/test/scala/just/semver/matcher/SemVerMatchersSpec.scala

Close #131 - Rename `SemVer.parseUnsafe` to `SemVer.unsafeParse` to keep the consistency with other unsafe methods

Close #131 - Rename `SemVer.parseUnsafe` to `SemVer.unsafeParse` to keep the consistency with other unsafe methods

---

src/main/scala-2/just/semver/matcher/SemVerMatchers.scala
src/main/scala-3/just/semver/matcher/SemVerMatchers.scala
src/test/scala/just/semver/matcher/SemVerMatchersSpec.scala

Simplify rendering `List[SemVerMatcher.ParseError]` - now `SemVerMatchers.ParseErrors` contains `List[SemVerMatcher.ParseError]`

Simplify rendering `List[SemVerMatcher.ParseError]` - now `SemVerMatchers.ParseErrors` contains `List[SemVerMatcher.ParseError]`

---

src/main/scala-2/just/semver/ParseError.scala
src/main/scala-2/just/semver/matcher/SemVerMatchers.scala
src/main/scala-3/just/semver/ParseError.scala
src/main/scala-3/just/semver/matcher/SemVerMatchers.scala

Simplify `Either[SemVerMatchers.ParseErrors, SemVerMatchers]` => `Either[just.semver.ParseError, SemVerMatchers]`

Simplify `Either[SemVerMatchers.ParseErrors, SemVerMatchers]` => `Either[just.semver.ParseError, SemVerMatchers]`

---

changelogs/0.4.0.md

* Rename `SemVer.parseUnsafe` to `SemVer.unsafeParse` to keep the consistency with other `unsafe` methods (#131)
* Replace `Major`, `Minor` and `Patch` value classes with `opaque type` in Scala 3 (#129)
* Add `SemVerMatchers`, `SemVer.matches()` and `SemVer.unsafeMatches()` (#125)
* Remove `can-equal` (#102)
* Use Scala 3 syntax (#91)
***
* Publish to `s01.oss.sonatype.org` (the new Maven central) (#115)
* Stop uploading artifacts to GitHub Release (#113)
* Set up Codecov in GitHub Actions (#111)
* Upgrade `sbt-devoops` from `2.6.0` to `2.14.0` (#103) `2.14.0` => `2.15.0` (#121) `2.15.0` => `2.16.0` (#126)

just-semver v0.4.0

---

changelogs/0.5.0.md

* Add decimal version `DecVer` (`major.minor`) (#140)
```scala
import just.decver.DecVer
val decVer1 = DecVer.parse("1.17")
// Either[DecVer.ParseError, DecVer] = Right(DecVer(1,17))
decVer1.map(_.render)
// Either[DecVer.ParseError, String] = Right(1.17)
val decVer2 = DecVer.unsafeParse("1.17")
// DecVer = DecVer(1,17)
decVer2.render
// String = 1.17
val semVer = decVer2.toSemVer
// just.semver.SemVer = SemVer(1,17,0,None,None)
semVer.toDecVer
// just.decver.DecVer = DecVer(1,17)
DecVer.unsafeParse("1.16") < DecVer.unsafeParse("1.17")
// Boolean = true
DecVer.unsafeParse("1.16") == DecVer.unsafeParse("1.17")
// Boolean = false
DecVer.unsafeParse("1.16") > DecVer.unsafeParse("1.17")
// Boolean = false
val decVer = DecVer.unsafeParse("1.0")
// DecVer = DecVer(1,0)
decVer.increaseMinor
// …
```

just-semver v0.5.0

---

changelogs/0.6.0.md

* Support Scala.js (#160)
* Create a doc site (#156) - https://just-semver.kevinly.dev
* Modularize the project (#150)

just-semver v0.6.0

---

.scalafmt.conf
build.sbt

Update: build.sbt - Scala `3.0.0` => `3.0.2` / Hedgehog `0.10.1` for non Scala `3.0`
- Also change `.scalafmt.conf` to remove the rule for `:=`

Update: build.sbt - Scala 3.0.0 => 3.0.2 / Hedgehog 0.10.1 for non Scala 3.0

---

.github/workflows/build.yml
.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
.github/workflows/release.yml
build.sbt
project/build.properties
project/plugins.sbt

Close #187 - Bump sbt and Scala, and drop Scala 2.11
- Bump sbt to `1.9.6`
- Bump Scala to
- `2.12.17`
- `2.13.11`
- `3.1.3`
- Drop Scala `2.11` support

Close #187 - Bump sbt and Scala, and drop Scala 2.11

---

changelogs/0.7.0.md

* Bump sbt and Scala, and drop Scala `2.11` (#187)
* Bump sbt to `1.9.6`
* Bump Scala to
* `2.12.17`
* `2.13.11`
* `3.1.3`
* Drop Scala `2.11` support

just-semver v0.7.0

---

changelogs/0.8.0.md

> NOTE: This release is exactly the same as `0.7.0`. 
> 
> `0.8.0` was released because the release of `0.7.0` was not done properly.
* Bump sbt and Scala, and drop Scala `2.11` (#187)
* Bump sbt to `1.9.6`
* Bump Scala to
* `2.12.17`
* `2.13.11`
* `3.1.3`
* Drop Scala `2.11` support

just-semver v0.8.0

---

build.sbt
changelogs/0.9.0.md

> NOTE: This release is exactly the same as `0.7.0` and `0.8.0`. 
> 
> `0.9.0` was released because `0.7.0` and `0.8.0` were not released properly.
* Bump sbt and Scala, and drop Scala `2.11` (#187)
* Bump sbt to `1.9.6`
* Bump Scala to
* `2.12.17`
* `2.13.11`
* `3.1.3`
* Drop Scala `2.11` support

just-semver v0.9.0

---

changelogs/0.10.0.md

* Bump Scala (#191)
Bump Scala to
* `2.12.18`
* `2.13.12`
* `3.2.2`

just-semver v0.10.0

---

changelogs/0.11.0.md

* Bump bump Scala 3 to `3.3.0` (LTS) to solve #186 (#198)
* Bump Scala version to 3.3.0+ to avoid lazy val not working properly under GraalVM Native Image (#186)

just-semver v0.11.0

---

changelogs/0.12.0.md

* Bump Scala 3 to `3.3.1` (LTS) (#202)

just-semver v0.12.0

---

changelogs/0.13.0.md

just-semver v0.13.0

---

build.sbt

Update `build.sbt` - disable wart-remover and some `scalacOptions` in console

Update `build.sbt` - disable wart-remover and some `scalacOptions` in console

---

changelogs/1.0.0.md

* Add `just-semver-decver` module (#221)
***
* [`just-semver-decver`] Add `DecVerExt` which is `DecVer` with pre-release and build metadata (#223)
***
* Add `DecVerExtMatcher`, the matcher for `DecVerExt` (#225)
```scala
DecVerExtMatchers.unsafeParse("1.0 - 2.0").matches(DecVerExt.unsafeParse("1.0")) // true
DecVerExtMatchers.unsafeParse("1.0 - 2.0").matches(DecVerExt.unsafeParse("0.9")) // false
DecVerExtMatchers.unsafeParse("1.0 - 2.0").matches(DecVerExt.unsafeParse("2.0")) // true
DecVerExtMatchers.unsafeParse("1.0 - 2.0").matches(DecVerExt.unsafeParse("2.1")) // false
// and more...
```
***
* Replace `DecVer` with `DecVerExt`, and rename `DecVerExt` to `DecVer` (#230)
***
* Unable to parse version "25.1-jre-graal-sub-1" (#216)
```scala
SemVer.parse("25.1-jre-graal-sub-1")
```
Results …

just-semver v1.0.0

---

build.sbt
modules/just-semver-core/shared/src/main/scala-2/just/semver/Dsv.scala
modules/just-semver-core/shared/src/main/scala-3/just/semver/Dsv.scala
modules/just-semver-core/shared/src/test/scala/just/semver/DsvSpec.scala
modules/just-semver-decver/shared/src/main/scala-2/just/decver/DecVer.scala
modules/just-semver-decver/shared/src/main/scala-3/just/decver/DecVer.scala

Fix #245 - `Dsv.parse` doesn't fail when the given input contains non-ascii or non-digit chars

Fix #245 - `Dsv.parse` doesn't fail when the given input contains non-ascii or non-digit chars

---

changelogs/1.1.1.md
modules/just-semver-core/shared/src/test/scala/just/semver/DsvSpec.scala

* Fix: `Dsv.parse` doesn't fail when the given input contains non-ascii or non-digit chars (#245)

just-semver v1.1.1

---

.gitignore

Update `.gitignore` to exclude Metals configuration files and Bloop configuration files

Update `.gitignore` to exclude Metals configuration files and Bloop configuration files

---

website/package.json

Update website dependencies and browser targets
- Upgrade Docusaurus packages from 3.5.2 to 3.8.1
- Upgrade React and React DOM from 18.0.0 to 19.0.0
- Upgrade TypeScript from 5.5.2 to 5.6.2
- Expand browser compatibility targets for development:
- Chrome and Firefox from last 1 version to last 3 versions
- Safari from last 1 version to last 5 versions

Update website dependencies and browser targets

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml

Update GitHub Actions: Bump Node from 18.13.0 to 22.17.0 in doc site build

Update GitHub Actions: Bump Node from 18.13.0 to 22.17.0 in doc site build
