.build-scripts/build-project.sh, .build-scripts/env-info.sh, README.md, build.sbt, project/plugins.sbt
* Added: Coveralls and Bintray support and settings
* Added: Build status badge
=> Coveralls and Bintray support and settings

project/plugins.sbt
Changed: plugins.sbt - removed: sbt-devoops repo as it can be downloaded from sbt repo
=> Changed: plugins.sbt

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, README.md
Close #14 - Set up GitHub Actions for CI
=> Close #14 - Set up GitHub Actions for CI

build.sbt
Close #12 - Change group id for publishing to `io.kevinlee`
* Changed: Group ID - `kevinlee` => `io.kevinlee`
* Added: `homepage` and `scmInfo`
=> Close #12 - Change group id for publishing to io.kevinlee

src/main/scala/just/semver/SemVer.scala, src/main/scala/just/semver/SequenceBasedVersion.scala, src/test/scala/just/semver/SemVerSpec.scala
Close #22 - Move instance member methods to the companion object
=> Close #22 - Move instance member methods to the companion object

PULL_REQUEST_TEMPLATE.md
=> Close #24 - Add PR templates

src/main/scala/just/semver/AdditionalInfo.scala, src/main/scala/just/semver/Anh.scala, src/main/scala/just/semver/Dsv.scala, src/test/scala/just/semver/Gens.scala, src/test/scala/just/semver/SemVerSpec.scala
Close #28 - Change `AlphaNumHyphen` to `Anh` and `AlphaNumHyphenGroup` to `Dsv`
=> Close #28 - Change AlphaNumHyphen to Anh and AlphaNumHyphenGroup to Dsv

src/main/scala/just/semver/AdditionalInfo.scala, src/main/scala/just/semver/Dsv.scala
Use` just-fp`'s `EitherOps` instead of using `EitherCompat`
=> Use just-fp's EitherOps instead of using EitherCompat

build.sbt
=> Added: Ammonite-REPL

README.md
Updated: `README.md` - how to use (in progress)
=> Updated: README.md - how to use (in progress)

project/plugins.sbt
Upgraded: sbt-devoops: `1.0.0` => `1.0.1`
=> Upgraded: sbt-devoops: 1.0.0 => 1.0.1

build.sbt, project/plugins.sbt
Upgraded: sbt-devoops: `1.0.1` => `1.0.2`
=> Upgraded: sbt-devoops: 1.0.1 => 1.0.2

src/main/scala/just/semver/SemVer.scala, src/test/scala/just/semver/SemVerSpec.scala
=> Added: more test

src/main/scala/just/semver/SemVer.scala, src/test/scala/just/semver/SemVerSpec.scala
Close #36 - Add `increase` for `SemVer`
=> Close #36 - Add increase for SemVer

README.md
Updated: `README.md` - Maven central / Scaladex badges
=> Updated: README.md - Maven central / Scaladex badges

.github/workflows/release.yml, .github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh
=> Fixed: build scripts

project/build.properties
=> Upgraded: sbt 1.3.3 => 1.3.4

project/build.properties
=> Upgraded: sbt 1.3.4 => 1.3.6

build.sbt, project/plugins.sbt
Upgraded: sbt-devoops 1.0.2 => 1.0.3
=> Upgraded: sbt-devoops 1.0.2 => 1.0.3

.github/workflows/build.yml
Changed: GitHub Actions - Cross Scala version build using matrix
=> Changed: GitHub Actions - Cross Scala version build using matrix

project/build.properties
=> Upgraded - sbt 1.3.6 => 1.3.7

.github/workflows/sbt-build-simple.sh, .github/workflows/sbt-build.sh, project/build.properties
=> Upgraded: sbt 1.3.8 => 1.3.13

.github/workflows/release.yml, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-build.sh, project/build.properties
=> Upgraded: sbt 1.3.13 => 1.4.4

.github/workflows/build.yml, .github/workflows/release.yml, project/plugins.sbt
Fixed: GitHub Actions config files
=> Fixed: GitHub Actions config files

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, project/plugins.sbt
Close #62 - Support Scala 3.0.0-M1 and 3.0.0-M2
=> Close #62 - Support Scala 3.0.0-M1 and 3.0.0-M2

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, src/test/scala/just/semver/Gens.scala
Close #64 - Support Scala 3.0.0-M3
=> Close #64 - Support Scala 3.0.0-M3

project/build.properties
Upgraded: sbt `1.4.4` => `1.4.9`
=> Upgraded: sbt 1.4.4 => 1.4.9

.scalafmt.conf, project/plugins.sbt
=> Added: .scalafmt.conf

build.sbt
=> Updated: project config

.github/workflows/build.yml, .github/workflows/release.yml, .scalafmt.conf, build.sbt, project/plugins.sbt, src/test/scala/just/semver/Gens.scala
Close #72 - Support Scala `3.0.0-RC2`
* Also upgraded Scala `2.12.12` => `2.12.13` / `2.13.3` => `2.13.5`
=> Close #72 - Support Scala 3.0.0-RC2

.github/workflows/release.yml, build.sbt, project/ProjectInfo.scala, project/plugins.sbt
Close #75 - Use `sbt-ci-release` to release
=> Close #75 - Use sbt-ci-release to release

src/main/scala/just/semver/SemVer.scala, src/test/scala/just/semver/SemVerSpec.scala
Close #82 - Add a method to get `(Major, Minor, Patch)` from `SemVer`
=> Close #82 - Add a method to get (Major, Minor, Patch) from SemVer

build.sbt, src/main/scala-2.11/just/semver/Compat.scala, src/main/scala-2.12_2.13/just/semver/Compat.scala, src/main/scala-3/just/semver/Compat.scala, src/main/scala/just/Common.scala, src/main/scala/just/semver/AdditionalInfo.scala, src/main/scala/just/semver/Dsv.scala, src/test/scala/just/semver/Gens.scala, src/test/scala/just/semver/SemVerSpec.scala
Close #86 - Make `just-semver` 0-dependency project
* Removed: `just-fp`
=> Close #86 - Make just-semver 0-dependency project

.scalafmt.conf, src/main/scala-2.11/just/semver/Compat.scala, src/main/scala/just/Common.scala, src/main/scala/just/semver/AdditionalInfo.scala, src/main/scala/just/semver/Anh.scala, src/main/scala/just/semver/Dsv.scala, src/main/scala/just/semver/ParseError.scala, src/main/scala/just/semver/SemVer.scala, src/test/scala/just/GenPlus.scala, src/test/scala/just/semver/AlphaNumHyphenSpec.scala, src/test/scala/just/semver/Gens.scala, src/test/scala/just/semver/SemVerMajorSpec.scala, src/test/scala/just/semver/SemVerMinorSpec.scala, src/test/scala/just/semver/SemVerPatchSpec.scala, src/test/scala/just/semver/SemVerSpec.scala
Updated: `.scalafmt.conf` `2.7.5` => `3.0.0-RC3` and formatting
=> Updated: .scalafmt.conf 2.7.5 => 3.0.0-RC3 and formatting

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/task-template.md
Updated: GitHub issue templates
=> Updated: GitHub issue templates

.github/workflows/build.yml, .scalafmt.conf, build.sbt, src/main/scala-2/just/Common.scala, src/main/scala-2/just/semver/AdditionalInfo.scala, src/main/scala-2/just/semver/Anh.scala, src/main/scala-2/just/semver/Dsv.scala, src/main/scala-2/just/semver/ParseError.scala, src/main/scala-2/just/semver/SemVer.scala, src/main/scala-3/just/Common.scala, src/main/scala-3/just/semver/AdditionalInfo.scala, src/main/scala-3/just/semver/Anh.scala, src/main/scala-3/just/semver/Dsv.scala, src/main/scala-3/just/semver/ParseError.scala, src/main/scala-3/just/semver/SemVer.scala, src/test/scala/just/semver/Gens.scala
Close #91 - Use Scala 3 syntax
=> Close #91 - Use Scala 3 syntax

README.md
Updated: `README.md` - with the new version info
=> Updated: README.md - with the new version info

project/build.properties
Upgraded: sbt `1.5.2` => `1.5.3`
=> Upgraded: sbt 1.5.2 => 1.5.3

build.sbt, project/plugins.sbt
Upgraded: sbt-devoops `2.4.1` => `2.6.0`
=> Upgraded: sbt-devoops 2.4.1 => 2.6.0

project/plugins.sbt
Upgraded: sbt-scalafix `0.9.28` => `0.9.29`
=> Upgraded: sbt-scalafix 0.9.28 => 0.9.29

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-build-test.sh, .scalafmt.conf, build.sbt, src/main/scala-2.12_2.13/just/semver/Compat.scala, src/main/scala-2/just/semver/AdditionalInfo.scala, src/main/scala-2/just/semver/Dsv.scala, src/main/scala-2/just/semver/ParseError.scala, src/main/scala-2/just/semver/SemVer.scala, src/main/scala-3/just/semver/AdditionalInfo.scala, src/main/scala-3/just/semver/Compat.scala, src/main/scala-3/just/semver/Dsv.scala, src/main/scala-3/just/semver/ParseError.scala, src/main/scala-3/just/semver/SemVer.scala
Close #102 - Remove `can-equal`
=> Close #102 - Remove can-equal

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-all-with-coverage.sh, project/plugins.sbt
Close #111 - Set up Codecov in GitHub Actions
=> Close #111 - Set up Codecov in GitHub Actions

.github/workflows/release.yml
Close #113 - Stop uploading artifacts to GItHub Release
=> Close #113 - Stop uploading artifacts to GItHub Release

build.sbt, project/plugins.sbt
Close #115 - Publish to `s01.oss.sonatype.org` (the new Maven central)
=> Close #115 - Publish to s01.oss.sonatype.org (the new Maven central)

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build.sh, build.sbt, project/plugins.sbt
=> Fix #111 - Codecov setup

.github/workflows/build.yml
=> Add: GitHub Actions for PR

project/build.properties
Upgrade sbt `1.6.1` => `1.6.2`
=> Upgrade sbt 1.6.1 => 1.6.2

project/plugins.sbt
Upgrade: sbt-devoops `2.14.0` => `2.15.0`
=> Upgrade: sbt-devoops 2.14.0 => 2.15.0

project/plugins.sbt
Upgrade: sbt-devoops 2.15.0 => 2.16.0
=> Upgrade: sbt-devoops 2.15.0 => 2.16.0

README.md
Update: README.md with v0.4.0 info
=> Update: README.md with v0.4.0 info

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/sbt-build-all-with-coverage.sh, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-build-test.sh, .github/workflows/sbt-build.sh, build.sbt, project/ProjectInfo.scala, project/plugins.sbt, src/main/scala-3/just/Common.scala, src/main/scala-3/just/semver/AdditionalInfo.scala
Close #138 - Set up WartRemover for Scala 3
=> Close #138 - Set up WartRemover for Scala 3

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, src/main/scala-2.11/just/semver/Compat.scala, src/main/scala-2/just/decver/DecVer.scala, src/main/scala-2/just/semver/SemVer.scala, src/main/scala-3/just/decver/DecVer.scala, src/main/scala-3/just/semver/SemVer.scala, src/test/scala/just/decver/DecVerSpec.scala, src/test/scala/just/decver/Gens.scala, src/test/scala/just/semver/Gens.scala, src/test/scala/just/semver/SemVerSpec.scala
Close #140 - Add decimal version (`major.minor`)
=> Close #140 - Add decimal version DecVer (major.minor)

README.md
Update: `README.md` - fix typo
=> Update: README.md - fix typo

project/plugins.sbt
Upgrade sbt-devoops 2.16.0 => 2.22.0
=> Upgrade sbt-devoops 2.16.0 => 2.22.0

project/plugins.sbt
Upgrade sbt-scoverage `1.9.2` => `1.9.3`
=> Upgrade sbt-scoverage 1.9.2 => 1.9.3

.scalafix.conf, project/plugins.sbt
Upgrade sbt-scalafix `0.9.29` => `0.10.1`
=> Upgrade sbt-scalafix 0.9.29 => 0.10.1

build.sbt
Close #150 - Modularize the project - fix missing settings
=> Close #150 - Modularize the project - fix missing settings

.scalafmt.conf
Update: `.scalafmt.conf` - `3.4.3` => `3.5.9`
=> Update: .scalafmt.conf - 3.4.3 => 3.5.9

build.sbt
Upgrade: hedgehog `0.8.0` => `0.9.0`
=> Upgrade: hedgehog 0.8.0 => 0.9.0

build.sbt, docs/intro.md
Close #156 - Create a doc site - update docs with the latest version info
=> Close #156 - Create a doc site - update docs with the latest version info

docs/intro.md
Update: docs with Scala.js info
=> Update: docs with Scala.js info

project/build.properties, project/plugins.sbt
Bump sbt `1.7.2` => `1.8.0-RC1`
=> Bump sbt 1.7.2 => 1.8.0-RC1

.scalafmt.conf
Update: `.scalafmt.conf` `3.5.9` => `3.6.1`
=> Update: .scalafmt.conf 3.5.9 => 3.6.1

project/build.properties
Upgrade: sbt `1.8.0-RC1` => `1.8.0`
=> Upgrade: sbt 1.8.0-RC1 => 1.8.0

project/build.properties
=> Bump sbt 1.8.0 => 1.8.2

project/build.properties
=> Bump sbt to 1.8.3

build.sbt
Update doc - supported versions
=> Update doc - supported versions

build.sbt, docs/intro.md
Update docs - update artifact name
=> Update docs - update artifact name

.github/workflows/build.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml, build.sbt
Close #191 - Bump Scala
Bump Scala to
- `2.12.18`
- `2.13.12`
- `3.2.2`
=> Close #191 - Bump Scala

docs/intro.md
Update docs - with the latest version info
=> Update docs - with the latest version info

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Close #198 - Bump bump Scala 3 to `3.3.0` (LTS) to solve #186
=> Close #198 - Bump bump Scala 3 to `3.3.0` (LTS) to solve #186

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Close #202 - Bump Scala 3 to `3.3.1` (LTS)
=> Close #202 - Bump Scala 3 to `3.3.1` (LTS)

website/.gitignore
Update: `.gitignore` for Docusaurus - Add `package-lock.json`
=> Update: .gitignore for Docusaurus - Add package-lock.json

build.sbt, project/plugins.sbt
Close #208 - Support Scala Native
=> Close #208 - Support Scala Native

project/build.properties
=> Bump sbt to 1.9.7

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt, modules/just-semver-core/shared/src/main/scala-2/just/Common.scala, modules/just-semver-core/shared/src/main/scala/just/semver/parser/Parser.scala, project/plugins.sbt
Bump sbt plugins
* sbt-docusaur to 0.15.0
* sbt-devoops to 3.0.0
=> Bump sbt plugins

build.sbt
=> Fix broken document build

build.sbt
Close #221 - Add `just-semver-decver` module
=> Close #221 - Add `just-semver-decver` module

modules/just-semver-core/shared/src/test/scala/just/semver/CommonGens.scala, modules/just-semver-core/shared/src/test/scala/just/semver/Gens.scala, modules/just-semver-core/shared/src/test/scala/just/semver/SemVerSpec.scala, modules/just-semver-core/shared/src/test/scala/just/semver/matcher/Gens.scala, modules/just-semver-core/shared/src/test/scala/just/semver/matcher/SemVerMatchersSpec.scala, modules/just-semver-decver/shared/src/main/scala-2/just/decver/DecVerExt.scala, modules/just-semver-decver/shared/src/main/scala-2/just/decver/matcher/DecVerExtComparison.scala, modules/just-semver-decver/shared/src/main/scala-2/just/decver/matcher/DecVerExtMatcher.scala, modules/just-semver-decver/shared/src/main/scala-2/just/decver/matcher/DecVerExtMatchers.scala, modules/just-semver-decver/shared/src/main/scala-3/just/decver/DecVerExt.scala, modules/just-semver-decver/shared/src/main/scala-3/just/decver/matcher/DecVerExtComparison.scala, modules/just-semver-decver/shared/src/main/scala-3/just/decver/matcher/DecVerExtMatcher.scala, modules/just-semver-decver/shared/src/main/scala-3/just/decver/matcher/DecVerExtMatchers.scala, modules/just-semver-decver/shared/src/test/scala/just/decver/DecVerExtGens.scala, modules/just-semver-decver/shared/src/test/scala/just/decver/DecVerExtSpec.scala, modules/just-semver-decver/shared/src/test/scala/just/decver/matcher/DecVerExtComparisonSpec.scala, modules/just-semver-decver/shared/src/test/scala/just/decver/matcher/DecVerExtMatcherSpec.scala, modules/just-semver-decver/shared/src/test/scala/just/decver/matcher/DecVerExtMatchersSpec.scala, modules/just-semver-decver/shared/src/test/scala/just/decver/matcher/Gens.scala
Close #225 - Add `DecVerExtMatcher`, the matcher for `DecVerExt`
=> Close #225 - Add `DecVerExtMatcher`, the matcher for `DecVerExt`

modules/just-semver-core/shared/src/test/scala/just/semver/SemVerSpec.scala, modules/just-semver-core/shared/src/test/scala/just/semver/matcher/SemVerMatcherSpec.scala, modules/just-semver-core/shared/src/test/scala/just/semver/matcher/SemVerMatchersSpec.scala
=> Update test logs

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, project/plugins.sbt, website/docusaurus.config.ts, website/package.json
Bump Docusaurus to 3.5.2 and sbt-devoops to 3.1.0
=> Bump Docusaurus to 3.5.2 and sbt-devoops to 3.1.0

.github/workflows/coverage.yml, codecov.yml
Add codecov config including GitHub Actions setup
=> Add codecov config including GitHub Actions setup

.github/workflows/coverage.yml
Update GitHub Actions: codecov config
=> Update GitHub Actions: codecov config

build.sbt, project/plugins.sbt
Close #239 - Support Scala Native
=> Close #239 - Support Scala Native

changelogs/1.1.0.md
=> just-semver v1.1.0

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/release.yml
Update GitHub Actions: Replace `olafurpg/setup-scala` with `actions/setup-java` and `sbt/setup-sbt`
=> Update GitHub Actions: Replace `olafurpg/setup-scala` with `actions/setup-java` and `sbt/setup-sbt`

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml, build.sbt, modules/just-semver-core/shared/src/main/scala-3/just/semver/ParseError.scala, modules/just-semver-decver/shared/src/main/scala-3/just/decver/DecVer.scala, project/build.properties, project/plugins.sbt
* Update Scala.js to 1.18.2, Scala Native to 0.5.7, and Scala versions
* Update Scala.js from 1.13.0 to 1.18.2
* Update Scala Native from 0.5.2 to 0.5.7
* Update Scala 2.13.12 to 2.13.16
* Update scala-collection-compat from 2.12.0 to 2.13.0
* Update Hedgehog from 0.9.0 to 0.11.0
* Bump sbt to 1.10.11
* Update Scala version in GitHub Actions settings from 2.13.11 to 2.13.16 and Scala 3.3.1 to 3.3.5
* Update sbt plugins:
- sbt-scalafix: 0.10.4 -> 0.12.0
- sbt-mdoc: 2.3.7 -> 2.5.2
- sbt-scalajs-crossproject: 1.3.1 -> 1.3.2
=> Update library versions

project/plugins.sbt
Upgrade sbt-docusaur to version 0.17.0 and sbt-devoops to 3.2.0
=> Upgrade sbt-docusaur to version 0.17.0 and sbt-devoops to 3.2.0

.github/workflows/release.yml
Update GitHub Actions workflow to enable snapshot publishing
=> Update GitHub Actions workflow to enable snapshot publishing

project/build.properties
=> Bump sbt to 1.11.7
